version: '2'
volumes:
  resin-data:
  node-red-data:
  grafana-data:
  influxdb-data:
  influxdb-etc:

services:
  node-red:
    build: ./node-red
    volumes:
      - 'resin-data:/data'
    restart: always
    privileged: true
    network_mode: host
    labels:
      io.balena.features.supervisor-api: '1'
    environment:
      - 'USERNAME=balena'
      - 'PASSWORD=balena'
      - 'ENCRIPTION_KEY=balena'
    cap_add:
      - SYS_RAWIO
    devices:
      - '/dev/mem:/dev/mem'
      - '/dev/gpiomem:/dev/gpiomem'
      - '/dev/i2c-1:/dev/i2c-1'
    ports:
      - 80:80
  # ------------------------------------------------------------------------------------
  # Influxdb
  # ------------------------------------------------------------------------------------
  influxdb:
    image: influxdb:2
    container_name: influxdb
    restart: unless-stopped
    ports:
      - '8086:8086'
    volumes:
      - influxdb-data:/var/lib/influxdb
      - influxdb-etc:/etc/influxdb

  # ------------------------------------------------------------------------------------
  # Grafana
  # ------------------------------------------------------------------------------------
  grafana:
    #image: balenablocks/dashboard
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - '8080:3000'
    volumes:
      - 'grafana-data:/data'
